"""a orden compra se le agrega img para comprobante

Revision ID: 20c80b1ff7dc
Revises: d6f1e6b121c3
Create Date: 2025-01-09 23:08:01.632119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c80b1ff7dc'
down_revision = 'd6f1e6b121c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('OrdenCompra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comprobanteImg_url', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('OrdenCompra', schema=None) as batch_op:
        batch_op.drop_column('comprobanteImg_url')

    # ### end Alembic commands ###
